name: Build & Push Execution Environment

on:
  push:
    paths:
      - 'execution-environment/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ee:
    runs-on: ubuntu-latest
    env:   # ðŸ‘ˆ forÃ§a docker
      ANSIBLE_BUILDER_CONTAINER_RUNTIME: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible Builder
        run: pip install ansible-builder==3.*

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Execution Environment
        run: |
          cd execution-environment
          ansible-builder build \
            --container-runtime=docker \
            -t quay.io/clecioantao/aap-ee:latest \
            -t quay.io/clecioantao/aap-ee:${{ github.sha }} \
            -f execution-environment.yml

      - name: Push to Quay.io (latest)
        run: docker push quay.io/clecioantao/aap-ee:latest

      - name: Push to Quay.io (commit SHA)
        run: docker push quay.io/clecioantao/aap-ee:${{ github.sha }}
